"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { BookOpen, Check, ChevronDown, Clock3, FileText, GraduationCap, Minus, Plus, Save, Sparkles, Target, ToggleLeft } from "lucide-react";
import { PageHeader } from "@/components/page-header";

const questionTypes = ["Múltipla escolha", "Verdadeiro ou falso", "Questões abertas"];

export default function CreateQuizPage() {
  const [difficulty, setDifficulty] = useState("Ensino superior");
  const [count, setCount] = useState(20);
  const [types, setTypes] = useState<string[]>(["Múltipla escolha", "Verdadeiro ou falso"]);
  const [aiEnabled, setAiEnabled] = useState(true);
  const duration = useMemo(() => Math.ceil(count * 1.5), [count]);
  const toggleType = (type: string) => setTypes((current) => current.includes(type) ? current.filter((item) => item !== type) : [...current, type]);

  return <div>
    <PageHeader eyebrow="Novo quiz" title="Monte sua próxima revisão" description="Escolha o nível, o formato e os materiais. A Lumina organiza o restante." icon={Sparkles} action={<button className="secondary-button"><Save className="size-4" /> Salvar rascunho</button>} />
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_360px]">
      <div className="space-y-5">
        <section className="surface p-5 sm:p-6"><h2 className="section-title mb-5">Informações básicas</h2><div className="grid gap-4 md:grid-cols-2"><Field label="Disciplina"><button className="flex h-12 w-full items-center gap-3 rounded-xl border border-slate-200 bg-slate-50 px-4 text-left text-sm font-semibold text-navy focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-500"><GraduationCap className="size-4 text-blue-600" /> Direito Constitucional <ChevronDown className="ml-auto size-4" /></button></Field><Field label="Título do quiz"><input defaultValue="Direitos Fundamentais — Parte 1" maxLength={80} className="h-12 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 text-sm outline-none focus:border-blue-400 focus:ring-4 focus:ring-blue-500/10" /></Field></div><Field label="Descrição (opcional)" className="mt-4"><textarea defaultValue="Conceitos, classificação e aplicações dos direitos fundamentais na Constituição Federal de 1988." className="min-h-24 w-full resize-none rounded-xl border border-slate-200 bg-slate-50 p-4 text-sm leading-relaxed outline-none focus:border-blue-400 focus:ring-4 focus:ring-blue-500/10" /></Field></section>

        <section className="surface p-5 sm:p-6"><div className="mb-5"><h2 className="section-title">Nível de escolaridade</h2><p className="mt-1 text-xs text-slate-500">A dificuldade e a linguagem serão ajustadas para este nível.</p></div><div className="grid gap-3 sm:grid-cols-3">{["Ensino fundamental", "Ensino médio", "Ensino superior"].map((item) => <button key={item} onClick={() => setDifficulty(item)} className={`relative min-h-20 rounded-xl border p-3 text-left transition focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-500 ${difficulty === item ? "border-blue-500 bg-blue-50 text-blue-800" : "border-slate-200 bg-white text-slate-600 hover:border-blue-200"}`}><strong className="block text-sm">{item}</strong><small className="mt-1 block opacity-70">{item === "Ensino superior" ? "Aprofundado" : item === "Ensino médio" ? "Intermediário" : "Fundamentos"}</small>{difficulty === item && <Check className="absolute right-3 top-3 size-4 text-blue-600" />}</button>)}</div></section>

        <section className="surface p-5 sm:p-6"><div className="grid gap-7 md:grid-cols-[1fr_1.1fr]"><div><h2 className="section-title">Número de questões</h2><div className="mt-4 flex items-center gap-3"><button onClick={() => setCount(Math.max(5, count - 5))} className="grid size-11 place-items-center rounded-xl border border-slate-200 hover:bg-slate-50"><Minus className="size-4" /></button><strong className="min-w-20 text-center text-3xl text-navy">{count}</strong><button onClick={() => setCount(Math.min(50, count + 5))} className="grid size-11 place-items-center rounded-xl border border-slate-200 hover:bg-slate-50"><Plus className="size-4" /></button></div><input aria-label="Quantidade de questões" type="range" min="5" max="50" step="5" value={count} onChange={(event) => setCount(Number(event.target.value))} className="mt-5 w-full accent-blue-600" /></div><div><h2 className="section-title">Tipos de questão</h2><div className="mt-4 space-y-2">{questionTypes.map((type) => <label key={type} className={`flex min-h-11 items-center gap-3 rounded-xl border px-3 text-sm transition ${types.includes(type) ? "border-violet-300 bg-violet-50 text-violet-800" : "border-slate-200"}`}><input type="checkbox" className="size-4 accent-violet-600" checked={types.includes(type)} onChange={() => toggleType(type)} /><span className="font-medium">{type}</span></label>)}</div></div></div></section>

        <section className="surface p-5 sm:p-6"><div className="mb-5 flex items-center justify-between"><div><h2 className="section-title">Materiais de referência</h2><p className="mt-1 text-xs text-slate-500">A IA usará apenas os materiais selecionados.</p></div><Link href="/materials" className="text-xs font-bold text-blue-600">Gerenciar</Link></div><div className="grid gap-3 md:grid-cols-2"><MaterialChoice title="Constituição Federal de 1988.pdf" meta="PDF · 2,3 MB" selected /><MaterialChoice title="Direitos Fundamentais — Resumo.docx" meta="DOCX · 1,1 MB" selected /></div><button className="mt-3 flex min-h-12 w-full items-center justify-center gap-2 rounded-xl border border-dashed border-blue-300 text-sm font-semibold text-blue-700 hover:bg-blue-50"><Plus className="size-4" /> Adicionar materiais</button></section>

        <section className="surface flex flex-col gap-4 p-5 sm:flex-row sm:items-center sm:justify-between sm:p-6"><div className="flex gap-3"><span className="grid size-11 place-items-center rounded-xl bg-violet-50 text-violet-600"><Sparkles className="size-5" /></span><div><h2 className="section-title">Gerar perguntas com IA</h2><p className="mt-1 text-xs text-slate-500">Crie perguntas inéditas fundamentadas nos materiais.</p></div></div><button role="switch" aria-checked={aiEnabled} onClick={() => setAiEnabled(!aiEnabled)} className={`relative h-7 w-12 rounded-full transition ${aiEnabled ? "bg-blue-600" : "bg-slate-300"}`}><span className={`absolute top-1 size-5 rounded-full bg-white shadow transition ${aiEnabled ? "left-6" : "left-1"}`} /></button></section>
      </div>

      <aside className="space-y-4 xl:sticky xl:top-24 xl:self-start">
        <section className="surface overflow-hidden"><div className="border-b border-slate-100 bg-[linear-gradient(135deg,#f6f9ff,#f2efff)] p-5"><span className="eyebrow">Resumo do quiz</span><h2 className="mt-2 text-lg font-extrabold text-navy">Direitos Fundamentais</h2></div><div className="space-y-4 p-5"><Summary icon={<GraduationCap />} label="Nível" value={difficulty} /><Summary icon={<BookOpen />} label="Questões" value={`${count} questões`} /><Summary icon={<ToggleLeft />} label="Formatos" value={`${types.length} selecionados`} /><Summary icon={<FileText />} label="Materiais" value="2 arquivos" /><Summary icon={<Clock3 />} label="Duração estimada" value={`${duration} min`} /><Summary icon={<Target />} label="Modo" value="Estudo" /></div><div className="mx-5 mb-5 rounded-xl bg-blue-50 p-4"><p className="text-xs font-semibold text-blue-900">Distribuição prevista</p><div className="mt-3 flex h-2 overflow-hidden rounded-full"><span className="w-3/5 bg-violet-500" /><span className="w-1/4 bg-cyan-500" /><span className="flex-1 bg-orange-400" /></div><p className="mt-2 text-[10px] leading-relaxed text-blue-700">A distribuição final pode variar conforme o conteúdo dos materiais.</p></div><div className="border-t border-slate-100 p-5"><Link href="/quizzes/session" className="primary-button w-full"><Sparkles className="size-4" /> Gerar quiz</Link><p className="mt-3 text-center text-[10px] text-slate-500">Você poderá revisar as perguntas antes de publicar.</p></div></section>
      </aside>
    </div>
  </div>;
}

function Field({ label, children, className = "" }: { label: string; children: React.ReactNode; className?: string }) { return <label className={`block ${className}`}><span className="mb-2 block text-xs font-bold text-navy">{label}</span>{children}</label>; }
function MaterialChoice({ title, meta, selected }: { title: string; meta: string; selected?: boolean }) { return <button className={`flex items-center gap-3 rounded-xl border p-3 text-left transition ${selected ? "border-blue-300 bg-blue-50/50" : "border-slate-200"}`}><span className="grid size-9 place-items-center rounded-lg bg-red-50 text-red-500"><FileText className="size-4" /></span><span className="min-w-0 flex-1"><strong className="block truncate text-xs text-navy">{title}</strong><small className="text-[10px] text-slate-500">{meta}</small></span>{selected && <Check className="size-4 text-blue-600" />}</button>; }
function Summary({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <div className="flex items-center gap-3 text-xs"><span className="text-blue-600 [&>svg]:size-4">{icon}</span><span className="text-slate-500">{label}</span><strong className="ml-auto text-right text-navy">{value}</strong></div>; }
