"use client";

import Image from "next/image";
import { FormEvent, useState } from "react";
import { Bot, CheckCircle2, Clock3, Copy, FileText, History, MessageSquarePlus, Paperclip, Plus, Send, Sparkles, ThumbsDown, ThumbsUp } from "lucide-react";

type Message = { role: "user" | "assistant"; text: string };

export default function ChatPage() {
  const [input, setInput] = useState("");
  const [messages, setMessages] = useState<Message[]>([
    { role: "user", text: "Quais são os princípios fundamentais do Direito Administrativo segundo o meu material?" },
    { role: "assistant", text: "Segundo os materiais selecionados, os cinco princípios expressos são Legalidade, Impessoalidade, Moralidade, Publicidade e Eficiência — o conhecido LIMPE. Eles aparecem no caput do art. 37 da Constituição Federal e orientam toda a atuação da Administração Pública." },
  ]);
  const submit = (event: FormEvent) => { event.preventDefault(); const value=input.trim(); if(!value) return; setMessages([...messages,{role:"user",text:value},{role:"assistant",text:"Encontrei referências relevantes nos materiais ativos. Em uma integração de produção, esta resposta será gerada pela IA com citações precisas das páginas consultadas."}]); setInput(""); };
  return <div className="grid min-h-[calc(100vh-8rem)] gap-5 xl:grid-cols-[minmax(0,1fr)_330px]">
    <section className="surface flex min-h-[720px] flex-col overflow-hidden"><header className="flex flex-wrap items-center gap-3 border-b border-slate-100 p-5"><span className="grid size-11 place-items-center rounded-xl bg-violet-50 text-violet-600"><Bot className="size-5" /></span><div><div className="flex items-center gap-2"><h1 className="text-xl font-extrabold tracking-tight text-navy">Tutora Lumina</h1><span className="rounded-full bg-emerald-50 px-2 py-1 text-[10px] font-bold text-emerald-700">Online</span></div><p className="mt-1 text-xs text-slate-500">Respostas fundamentadas nos seus materiais.</p></div><button onClick={() => setMessages([])} className="secondary-button ml-auto min-h-10 px-3"><MessageSquarePlus className="size-4" /> Nova conversa</button></header>
      <div aria-live="polite" className="flex-1 space-y-6 overflow-y-auto bg-[radial-gradient(circle_at_50%_0%,rgba(36,88,255,.045),transparent_35%)] p-5 sm:p-7">{messages.length === 0 ? <div className="grid h-full place-items-center text-center"><div><span className="mx-auto grid size-16 place-items-center rounded-3xl bg-blue-50 text-blue-600"><Sparkles /></span><h2 className="mt-4 font-bold text-navy">O que vamos aprender?</h2><p className="mt-2 text-sm text-slate-500">Pergunte sobre qualquer material da sua biblioteca.</p></div></div> : messages.map((message,index) => message.role === "user" ? <div key={index} className="ml-auto max-w-2xl"><div className="rounded-2xl rounded-br-md bg-blue-600 px-5 py-4 text-sm leading-relaxed text-white shadow-lg shadow-blue-200">{message.text}</div><p className="mt-1 text-right text-[10px] text-slate-400">Você · agora</p></div> : <div key={index} className="flex max-w-3xl gap-3"><Image src="/robozinho-student.png" alt="Lumina" width={42} height={42} className="size-10 shrink-0 rounded-xl bg-blue-100 object-cover object-top" /><div className="min-w-0"><div className="rounded-2xl rounded-tl-md border border-slate-200 bg-white p-5 text-sm leading-7 text-slate-700 shadow-sm"><p>{message.text}</p><div className="mt-5 border-t border-slate-100 pt-4"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">Fontes consultadas</p><div className="mt-2 flex flex-wrap gap-2"><Source title="Constituição Federal.pdf" page="p. 37" /><Source title="Resumo Administrativo.pdf" page="p. 12" /></div></div></div><div className="mt-2 flex gap-1"><ActionButton label="Resposta útil"><ThumbsUp /></ActionButton><ActionButton label="Resposta não útil"><ThumbsDown /></ActionButton><ActionButton label="Copiar"><Copy /></ActionButton></div></div></div>)}</div>
      <div className="border-t border-slate-100 bg-white p-4 sm:p-5"><div className="mb-3 flex gap-2 overflow-x-auto pb-1"><Suggestion text="Explique de outro jeito" onClick={setInput} /><Suggestion text="Crie 5 questões sobre isso" onClick={setInput} /><Suggestion text="Mostre um exemplo prático" onClick={setInput} /></div><form onSubmit={submit} className="rounded-2xl border border-blue-200 bg-slate-50 p-3 focus-within:border-blue-500 focus-within:ring-4 focus-within:ring-blue-500/10"><textarea value={input} onChange={(event)=>setInput(event.target.value)} placeholder="Pergunte algo à Lumina..." className="min-h-16 w-full resize-none bg-transparent px-2 text-sm outline-none" /><div className="flex items-center gap-2"><button type="button" className="secondary-button min-h-9 px-3 text-xs"><Paperclip className="size-4" /> Anexar</button><button type="button" className="secondary-button min-h-9 px-3 text-xs"><Plus className="size-4" /> Materiais</button><button type="submit" aria-label="Enviar mensagem" className="ml-auto grid size-10 place-items-center rounded-xl bg-blue-600 text-white shadow-md transition hover:bg-blue-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-500 focus-visible:ring-offset-2"><Send className="size-4" /></button></div></form><p className="mt-2 flex items-center gap-1.5 text-[10px] text-slate-400"><Sparkles className="size-3 text-violet-500" />A Lumina pode cometer erros. Confira as fontes indicadas.</p></div>
    </section>
    <aside className="space-y-5"><section className="surface p-5"><div className="flex items-center justify-between"><h2 className="section-title">Contexto da conversa</h2><span className="rounded-full bg-emerald-50 px-2 py-1 text-[10px] font-bold text-emerald-700">4 ativos</span></div><p className="mt-2 text-xs leading-relaxed text-slate-500">A Lumina consulta estes materiais para elaborar a resposta.</p><div className="mt-4 space-y-2"><ContextFile title="Direito Administrativo — Resumo.pdf" page="p. 12" /><ContextFile title="Teoria e Questões.docx" page="p. 8" /><ContextFile title="Constituição Federal.pdf" page="p. 37" /></div><button className="mt-3 flex min-h-10 w-full items-center justify-center gap-2 rounded-xl bg-blue-50 text-xs font-bold text-blue-700 hover:bg-blue-100"><Plus className="size-4" /> Adicionar materiais</button></section><section className="overflow-hidden rounded-2xl border border-violet-200 bg-[linear-gradient(145deg,#f9f7ff,#eef6ff)] p-5"><Sparkles className="size-5 text-violet-600" /><h2 className="mt-3 font-bold text-violet-800">Como eu ajudo</h2><div className="mt-4 space-y-2.5 text-xs text-slate-600"><Feature text="Respostas baseadas nos seus documentos" /><Feature text="Citações com páginas e fontes" /><Feature text="Explicações no seu nível de ensino" /><Feature text="Criação de perguntas para revisão" /></div></section><section className="surface p-5"><div className="flex items-center justify-between"><h2 className="section-title">Conversas recentes</h2><History className="size-4 text-blue-600" /></div><div className="mt-3 divide-y divide-slate-100"><HistoryItem title="Princípios do Direito Administrativo" time="10:32" /><HistoryItem title="Ato administrativo e requisitos" time="Ontem" /><HistoryItem title="Licitações: modalidades e tipos" time="8 jul" /><HistoryItem title="Responsabilidade civil do Estado" time="5 jul" /></div></section></aside>
  </div>;
}
function Source({title,page}:{title:string;page:string}) { return <span className="inline-flex items-center gap-2 rounded-lg border border-slate-200 bg-slate-50 px-2.5 py-2 text-[10px] text-slate-600"><FileText className="size-3.5 text-red-500" /><strong>{title}</strong>{page}</span> }
function ActionButton({label,children}:{label:string;children:React.ReactNode}) { return <button aria-label={label} title={label} className="grid size-8 place-items-center rounded-lg text-slate-400 hover:bg-slate-100 hover:text-blue-600 [&>svg]:size-3.5">{children}</button> }
function Suggestion({text,onClick}:{text:string;onClick:(value:string)=>void}) { return <button onClick={()=>onClick(text)} className="shrink-0 rounded-full border border-slate-200 bg-white px-3 py-2 text-[11px] font-semibold text-slate-600 hover:border-blue-300 hover:text-blue-700">{text}</button> }
function ContextFile({title,page}:{title:string;page:string}) { return <button className="flex w-full items-center gap-3 rounded-xl border border-slate-100 p-3 text-left hover:border-blue-200"><FileText className="size-4 shrink-0 text-red-500" /><span className="min-w-0 flex-1 truncate text-[11px] font-semibold text-navy">{title}</span><small className="text-[10px] text-slate-400">{page}</small></button> }
function Feature({text}:{text:string}) { return <p className="flex gap-2"><CheckCircle2 className="size-4 shrink-0 text-emerald-500" />{text}</p> }
function HistoryItem({title,time}:{title:string;time:string}) { return <button className="flex w-full items-center gap-2 py-3 text-left"><Clock3 className="size-3.5 text-slate-400" /><span className="min-w-0 flex-1 truncate text-[11px] font-medium text-navy">{title}</span><small className="text-[9px] text-slate-400">{time}</small></button> }
