"use client";

import Link from "next/link";
import { useState } from "react";
import { ArrowLeft, ArrowRight, Bookmark, BookOpen, Bot, Check, Clock3, Flag, Pause, Sparkles, Target } from "lucide-react";

const options = ["A forma federativa de Estado.", "A separação dos Poderes.", "Os direitos e garantias individuais.", "A periodicidade das eleições.", "A vedação ao retrocesso social."];

export default function QuizSessionPage() {
  const [selected, setSelected] = useState(1);
  const [marked, setMarked] = useState(false);
  return <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_330px]">
    <div className="space-y-5">
      <header className="surface p-5"><div className="flex flex-wrap items-center gap-3 border-b border-slate-100 pb-4"><Link href="/quizzes" aria-label="Voltar aos quizzes" className="grid size-9 place-items-center rounded-lg hover:bg-slate-100"><ArrowLeft className="size-4" /></Link><div className="min-w-0 flex-1"><p className="text-xs text-slate-500">Direito Constitucional</p><h1 className="truncate text-base font-bold text-navy">Revisão Geral — Direitos Fundamentais</h1></div><button className="secondary-button min-h-10 px-3"><Pause className="size-4" /> Pausar</button></div><div className="grid gap-4 pt-4 sm:grid-cols-3"><Info label="Questão" value="8 / 20"><div className="mt-2 h-1.5 rounded-full bg-slate-100"><div className="h-full w-2/5 rounded-full bg-blue-600" /></div></Info><Info label="Tempo restante" value="01:12:45" icon={<Clock3 />} /><Info label="Disciplina" value="Direito Constitucional" icon={<BookOpen />} /></div></header>
      <main className="surface p-5 sm:p-7 lg:p-8"><span className="inline-flex items-center gap-2 rounded-full bg-violet-50 px-3 py-1.5 text-xs font-bold text-violet-700"><Target className="size-3.5" /> Múltipla escolha</span><h2 className="mt-5 text-xl font-extrabold leading-snug tracking-[-.025em] text-navy sm:text-2xl">A Constituição Federal de 1988 estabelece como cláusula pétrea:</h2><p className="mt-3 text-sm text-slate-500">Selecione a alternativa correta.</p><div className="mt-6 space-y-3">{options.map((option, index) => <button key={option} onClick={() => setSelected(index)} className={`flex min-h-14 w-full items-center gap-4 rounded-xl border px-4 text-left text-sm font-medium transition focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-500 ${selected === index ? "border-blue-500 bg-blue-50/60 text-blue-900 shadow-[inset_3px_0_0_#2458ff]" : "border-slate-200 bg-white text-navy hover:border-blue-200 hover:bg-slate-50"}`}><span className={`grid size-5 shrink-0 place-items-center rounded-full border ${selected === index ? "border-blue-600 bg-blue-600 text-white" : "border-slate-300"}`}>{selected === index && <Check className="size-3" />}</span>{option}</button>)}</div><div className="mt-6 flex flex-wrap items-center justify-between gap-3 border-y border-slate-100 py-4"><button onClick={() => setMarked(!marked)} className={`secondary-button min-h-10 px-3 ${marked ? "border-orange-300 bg-orange-50 text-orange-700" : ""}`}><Bookmark className={`size-4 ${marked ? "fill-current" : ""}`} />{marked ? "Marcada" : "Marcar para revisar"}</button><Link href="/chat" className="inline-flex min-h-10 items-center gap-2 rounded-xl px-3 text-sm font-semibold text-violet-600 hover:bg-violet-50"><Sparkles className="size-4" /> Explicar com a Lumina</Link></div><div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-3"><button className="secondary-button"><ArrowLeft className="size-4" /> Anterior</button><button className="secondary-button hidden sm:inline-flex"><Flag className="size-4" /> Pular</button><button className="primary-button">Próxima <ArrowRight className="size-4" /></button></div></main>
      <div className="rounded-2xl border border-violet-200 bg-violet-50/60 p-5"><div className="flex gap-4"><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-white text-violet-600"><Bot className="size-5" /></span><div><strong className="text-sm text-navy">Questões abertas também entram na revisão</strong><p className="mt-1 text-xs leading-relaxed text-slate-600">A Lumina avalia clareza, precisão e conceitos-chave, mostrando como melhorar sua resposta.</p></div></div></div>
    </div>
    <aside className="space-y-5 xl:sticky xl:top-24 xl:self-start"><section className="surface p-5"><h2 className="section-title">Mapa de questões</h2><div className="mt-4 flex flex-wrap gap-3 text-[10px] text-slate-500"><span className="flex items-center gap-1"><i className="size-2 rounded-full bg-emerald-500" />Respondida</span><span className="flex items-center gap-1"><i className="size-2 rounded-full bg-blue-600" />Atual</span><span className="flex items-center gap-1"><i className="size-2 rounded-full border border-slate-400" />Pendente</span></div><div className="mt-5 grid grid-cols-5 gap-2">{Array.from({ length: 20 }, (_, i) => i + 1).map((number) => <button key={number} className={`aspect-square rounded-xl border text-xs font-bold transition hover:border-blue-400 ${number < 8 ? "border-emerald-200 bg-emerald-50 text-emerald-700" : number === 8 ? "border-blue-600 bg-blue-600 text-white shadow-lg shadow-blue-200" : number === 12 && marked ? "border-orange-300 bg-orange-50 text-orange-600" : "border-slate-200 text-slate-600"}`}>{number}</button>)}</div></section><section className="surface p-5"><div className="flex items-center justify-between"><h2 className="section-title">Nesta sessão</h2><span className="text-xs font-bold text-blue-600">78%</span></div><div className="mt-5 flex items-center gap-5"><div className="grid size-20 shrink-0 place-items-center rounded-full bg-[conic-gradient(#2458ff_0_78%,#e8edf5_78%)]"><div className="grid size-15 place-items-center rounded-full bg-white text-xl font-extrabold">78%</div></div><div><p className="text-xs text-slate-500">Aproveitamento</p><strong className="mt-1 block text-sm text-emerald-600">Muito bom!</strong></div></div><div className="mt-5 grid grid-cols-3 gap-2 text-center"><Score value="15" label="Acertos" tone="green" /><Score value="4" label="Erros" tone="red" /><Score value="1" label="Marcada" tone="orange" /></div></section><section className="overflow-hidden rounded-2xl border border-blue-200 bg-[linear-gradient(145deg,#eef6ff,#f3efff)] p-5"><Sparkles className="size-5 text-violet-600" /><h2 className="mt-3 font-bold text-violet-800">Dica da Lumina</h2><p className="mt-2 text-xs leading-relaxed text-slate-600">As cláusulas pétreas estão no Art. 60, §4º e não podem ser abolidas por emenda.</p><Link href="/chat" className="mt-4 inline-flex items-center gap-2 text-xs font-bold text-blue-600">Entender este assunto <ArrowRight className="size-3" /></Link></section></aside>
  </div>;
}
function Info({ label, value, icon, children }: { label:string; value:string; icon?:React.ReactNode; children?:React.ReactNode }) { return <div className="border-slate-100 sm:border-r sm:pr-4 last:border-0"><span className="text-[10px] font-semibold uppercase tracking-wider text-slate-400">{label}</span><div className="mt-1 flex items-center gap-2 text-sm font-bold text-navy"><span className="text-blue-600 [&>svg]:size-4">{icon}</span>{value}</div>{children}</div> }
function Score({ value, label, tone }: { value:string; label:string; tone:string }) { const color:Record<string,string>={green:"text-emerald-600",red:"text-red-500",orange:"text-orange-500"}; return <div className="rounded-xl bg-slate-50 p-3"><strong className={`block text-lg ${color[tone]}`}>{value}</strong><small className="text-[10px] text-slate-500">{label}</small></div> }
