"use client";
import { useState } from "react";
import { Bell, Bot, Check, Globe2, LockKeyhole, Moon, Palette, Settings, ShieldCheck, Sparkles, Sun } from "lucide-react";
import { PageHeader } from "@/components/page-header";

export default function SettingsPage(){ const [saved,setSaved]=useState(false); const [notifications,setNotifications]=useState(true); const [citations,setCitations]=useState(true); return <div><PageHeader eyebrow="Preferências" title="Configurações" description="Personalize sua experiência de estudo, notificações e uso da tutora de IA." icon={Settings} />{saved&&<div className="mb-4 flex items-center gap-2 rounded-xl bg-emerald-50 p-3 text-sm font-semibold text-emerald-700"><Check className="size-4"/>Preferências salvas.</div>}<div className="grid gap-5 xl:grid-cols-[220px_minmax(0,1fr)]"><aside className="surface h-fit p-2"><SettingNav icon={<Palette/>} label="Aparência" active/><SettingNav icon={<Bell/>} label="Notificações"/><SettingNav icon={<Bot/>} label="Tutora IA"/><SettingNav icon={<ShieldCheck/>} label="Privacidade"/><SettingNav icon={<LockKeyhole/>} label="Conta e segurança"/></aside><div className="space-y-5"><section className="surface p-5 sm:p-6"><h2 className="section-title">Aparência e idioma</h2><p className="mt-1 text-xs text-slate-500">Escolha como a Lumina aparece para você.</p><div className="mt-5 grid gap-3 sm:grid-cols-3"><Theme icon={<Sun/>} label="Claro" active/><Theme icon={<Moon/>} label="Escuro"/><Theme icon={<Sparkles/>} label="Sistema"/></div><div className="mt-5 max-w-md"><label className="mb-2 block text-xs font-bold text-navy">Idioma</label><button className="flex h-11 w-full items-center gap-2 rounded-xl border border-slate-200 px-3 text-sm text-navy"><Globe2 className="size-4 text-blue-600"/>Português (Brasil)<span className="ml-auto text-slate-400">⌄</span></button></div></section><section className="surface p-5 sm:p-6"><h2 className="section-title">Notificações</h2><div className="mt-5 divide-y divide-slate-100"><Toggle title="Lembretes de revisão" copy="Avise quando um quiz estiver pronto para ser repetido." value={notifications} setValue={setNotifications}/><Toggle title="Resumo semanal" copy="Receba um panorama do seu desempenho toda segunda-feira." value={true}/><Toggle title="Processamento de materiais" copy="Avise quando um arquivo estiver pronto para uso." value={true}/></div></section><section className="surface p-5 sm:p-6"><h2 className="section-title">Tutora de IA</h2><div className="mt-5 divide-y divide-slate-100"><Toggle title="Sempre mostrar fontes" copy="Inclui documentos e páginas usados em cada resposta." value={citations} setValue={setCitations}/><Toggle title="Adaptar ao nível de escolaridade" copy="Ajusta vocabulário e profundidade das explicações." value={true}/></div></section><div className="flex justify-end"><button onClick={()=>{setSaved(true);setTimeout(()=>setSaved(false),2500)}} className="primary-button">Salvar alterações</button></div></div></div></div> }
function SettingNav({icon,label,active=false}:{icon:React.ReactNode;label:string;active?:boolean}){return <button className={`flex h-11 w-full items-center gap-3 rounded-xl px-3 text-sm font-semibold [&>svg]:size-4 ${active?"bg-blue-50 text-blue-700":"text-slate-500 hover:bg-slate-50"}`}>{icon}{label}</button>}
function Theme({icon,label,active=false}:{icon:React.ReactNode;label:string;active?:boolean}){return <button className={`relative flex min-h-20 items-center gap-3 rounded-xl border p-4 text-sm font-semibold [&>svg]:size-5 ${active?"border-blue-500 bg-blue-50 text-blue-700":"border-slate-200 text-slate-500"}`}>{icon}{label}{active&&<Check className="absolute right-3 top-3 size-3!"/>}</button>}
function Toggle({title,copy,value,setValue}:{title:string;copy:string;value:boolean;setValue?:(v:boolean)=>void}){return <div className="flex items-center gap-4 py-4"><div className="flex-1"><strong className="block text-sm text-navy">{title}</strong><p className="mt-1 text-xs text-slate-500">{copy}</p></div><button role="switch" aria-checked={value} onClick={()=>setValue?.(!value)} className={`relative h-7 w-12 shrink-0 rounded-full ${value?"bg-blue-600":"bg-slate-300"}`}><span className={`absolute top-1 size-5 rounded-full bg-white shadow transition ${value?"left-6":"left-1"}`}/></button></div>}
