import { Award, BarChart3, BookOpen, Brain, CalendarDays, ChevronDown, Clock3, Flame, Target, TrendingUp, Trophy } from "lucide-react";
import { PageHeader } from "@/components/page-header";

const weekly = [42, 68, 55, 82, 66, 91, 74];
const subjects = [{name:"Direito Constitucional",score:85,questions:328,color:"bg-blue-600"},{name:"Direito Administrativo",score:78,questions:264,color:"bg-violet-500"},{name:"Português",score:72,questions:198,color:"bg-cyan-500"},{name:"Matemática",score:68,questions:173,color:"bg-amber-400"},{name:"Atualidades",score:60,questions:91,color:"bg-red-400"}];

export default function PerformancePage() { return <div><PageHeader eyebrow="Evolução" title="Seu desempenho" description="Entenda seus padrões, celebre avanços e descubra onde focar a próxima sessão." icon={BarChart3} action={<button className="secondary-button"><CalendarDays className="size-4" /> Últimos 30 dias <ChevronDown className="size-4" /></button>} />
  <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={<Target />} label="Aproveitamento" value="78%" delta="+6%" tone="blue" /><Metric icon={<BookOpen />} label="Questões" value="1.248" delta="+18%" tone="violet" /><Metric icon={<Clock3 />} label="Tempo de estudo" value="14h 32m" delta="+2h 30m" tone="cyan" /><Metric icon={<Flame />} label="Sequência" value="12 dias" delta="melhor: 18" tone="orange" /></section>
  <section className="mt-5 grid gap-5 xl:grid-cols-[1.55fr_.75fr]"><article className="surface p-5 sm:p-6"><div className="flex items-center justify-between"><div><h2 className="section-title">Ritmo de estudos</h2><p className="mt-1 text-xs text-slate-500">Questões respondidas por dia</p></div><span className="flex items-center gap-1 text-xs font-bold text-emerald-600"><TrendingUp className="size-4" /> +18%</span></div><div className="mt-7 flex h-56 items-end gap-3 sm:gap-5">{weekly.map((value,index)=><div key={index} className="flex flex-1 flex-col items-center gap-2"><div className="relative flex h-44 w-full items-end rounded-t-xl bg-slate-50"><div className={`w-full rounded-t-xl ${index===5?"bg-[linear-gradient(#2458ff,#6f5cff)]":"bg-blue-200"}`} style={{height:`${value}%`}}><span className="sr-only">{value} questões</span></div></div><span className="text-[10px] font-semibold text-slate-500">{["Seg","Ter","Qua","Qui","Sex","Sáb","Dom"][index]}</span></div>)}</div></article><article className="surface flex flex-col items-center justify-center p-6 text-center"><div className="grid size-40 place-items-center rounded-full bg-[conic-gradient(#2458ff_0_78%,#e8edf5_78%)]"><div className="grid size-30 place-items-center rounded-full bg-white"><span><strong className="block text-4xl tracking-tight text-navy">78%</strong><small className="text-slate-500">média geral</small></span></div></div><div className="mt-5 inline-flex items-center gap-2 rounded-full bg-emerald-50 px-3 py-1.5 text-xs font-bold text-emerald-700"><Award className="size-4" /> Acima de 72% dos alunos</div></article></section>
  <section className="mt-5 grid gap-5 xl:grid-cols-[1.15fr_.85fr]"><article className="surface p-5 sm:p-6"><div className="mb-6 flex items-center justify-between"><h2 className="section-title">Desempenho por disciplina</h2><span className="text-[10px] text-slate-400">Total: 1.054 questões</span></div><div className="space-y-5">{subjects.map(subject=><div key={subject.name} className="grid grid-cols-[minmax(140px,1fr)_1.3fr_48px] items-center gap-4"><div><strong className="block truncate text-xs text-navy">{subject.name}</strong><small className="text-[10px] text-slate-400">{subject.questions} questões</small></div><div className="h-2.5 rounded-full bg-slate-100"><div className={`h-full rounded-full ${subject.color}`} style={{width:`${subject.score}%`}} /></div><strong className="text-right text-sm text-navy">{subject.score}%</strong></div>)}</div></article><div className="space-y-5"><article className="surface p-5"><div className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-xl bg-violet-50 text-violet-600"><Brain className="size-5" /></span><div><h2 className="section-title">Insight da Lumina</h2><p className="text-[10px] text-slate-400">Baseado nas últimas 8 sessões</p></div></div><p className="mt-4 text-sm leading-relaxed text-slate-600">Você evoluiu bastante em <strong className="text-navy">Direito Constitucional</strong>. Para equilibrar a média, revise funções matemáticas e atualidades nesta semana.</p><button className="mt-4 text-xs font-bold text-blue-600">Criar plano de revisão →</button></article><article className="overflow-hidden rounded-2xl bg-[linear-gradient(135deg,#071a4f,#1744bd)] p-5 text-white"><Trophy className="size-6 text-yellow-300" /><h2 className="mt-4 text-lg font-bold">Novo recorde pessoal</h2><p className="mt-2 text-xs leading-relaxed text-blue-100">91 questões em um único dia. Continue assim para desbloquear a medalha “Ritmo de prova”.</p><div className="mt-4 h-2 rounded-full bg-white/15"><div className="h-full w-4/5 rounded-full bg-cyan-300" /></div></article></div></section>
</div> }
function Metric({icon,label,value,delta,tone}:{icon:React.ReactNode;label:string;value:string;delta:string;tone:string}) { const c:Record<string,string>={blue:"bg-blue-50 text-blue-600",violet:"bg-violet-50 text-violet-600",cyan:"bg-cyan-50 text-cyan-600",orange:"bg-orange-50 text-orange-500"}; return <article className="surface flex items-center gap-4 p-5"><span className={`grid size-12 place-items-center rounded-2xl ${c[tone]} [&>svg]:size-5`}>{icon}</span><div><p className="text-xs text-slate-500">{label}</p><div className="mt-1 flex items-baseline gap-2"><strong className="text-xl text-navy">{value}</strong><small className="text-[10px] font-bold text-emerald-600">{delta}</small></div></div></article> }
