"use client";

import { useRef, useState } from "react";
import { BookOpen, CheckCircle2, ChevronDown, File, FileText, Filter, Folder, FolderPlus, HardDrive, MoreVertical, Plus, Search, Sparkles, Star, UploadCloud } from "lucide-react";
import { PageHeader } from "@/components/page-header";

const materials = [
  { title: "Constituição Federal de 1988.pdf", subject: "Direito Constitucional", size: "12,4 MB", status: "Pronto", type: "PDF" },
  { title: "Direito Administrativo — Resumo.docx", subject: "Direito Administrativo", size: "1,8 MB", status: "Processando 65%", type: "DOCX" },
  { title: "Apostila Matemática.pdf", subject: "Matemática", size: "7,2 MB", status: "Pronto", type: "PDF" },
  { title: "Redação — Exemplos.pdf", subject: "Redação", size: "1,8 MB", status: "Resumido", type: "PDF" },
  { title: "Atualidades — Junho 2026.pdf", subject: "Atualidades", size: "3,1 MB", status: "Pronto", type: "PDF" },
  { title: "Quadro de fórmulas.jpg", subject: "Matemática", size: "2,6 MB", status: "Usado em quiz", type: "JPG" },
];

export default function MaterialsPage() {
  const inputRef = useRef<HTMLInputElement>(null);
  const [uploaded, setUploaded] = useState<string | null>(null);
  const [selected, setSelected] = useState(materials[0]);
  return <div><PageHeader eyebrow="Biblioteca" title="Seus materiais" description="Organize seus arquivos e transforme conteúdo passivo em aprendizado ativo." icon={BookOpen} action={<div className="flex gap-2"><button className="secondary-button"><FolderPlus className="size-4" /> Nova pasta</button><button onClick={() => inputRef.current?.click()} className="primary-button"><UploadCloud className="size-4" /> Enviar material</button></div>} />
    {uploaded && <div role="status" className="mb-4 flex items-center gap-3 rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-800"><CheckCircle2 className="size-4" /><strong>{uploaded}</strong> foi adicionado e já está sendo processado.</div>}
    <section className="mb-5 grid gap-4 xl:grid-cols-[1.2fr_.75fr_.75fr]"><button onClick={() => inputRef.current?.click()} className="group grid min-h-48 place-items-center rounded-2xl border border-dashed border-blue-300 bg-[linear-gradient(145deg,#f9fbff,#f1f5ff)] p-6 text-center transition hover:border-blue-500 hover:shadow-lg"><input ref={inputRef} type="file" accept=".pdf,.doc,.docx,.ppt,.pptx,.png,.jpg,.jpeg" className="hidden" onChange={(event) => setUploaded(event.target.files?.[0]?.name ?? null)} /><span><span className="mx-auto mb-3 grid size-12 place-items-center rounded-2xl bg-white text-blue-600 shadow-sm"><UploadCloud /></span><strong className="block text-sm text-navy">Arraste ou selecione seus arquivos</strong><small className="mt-1 block text-slate-500">PDF, DOCX, PPTX, PNG ou JPG · até 250 MB</small></span></button><SummaryCard icon={<FileText />} label="Total de materiais" value="24" detail="+4 esta semana"><div className="mt-5 space-y-2 text-xs text-slate-500"><p className="flex justify-between"><span>Prontos</span><strong className="text-navy">16</strong></p><p className="flex justify-between"><span>Processando</span><strong className="text-navy">2</strong></p><p className="flex justify-between"><span>Resumidos pela IA</span><strong className="text-navy">14</strong></p></div></SummaryCard><SummaryCard icon={<HardDrive />} label="Armazenamento" value="2,48 GB" detail="de 10 GB usados"><div className="mt-6 h-2 rounded-full bg-slate-100"><div className="h-full w-1/4 rounded-full bg-blue-600" /></div><p className="mt-2 text-right text-[10px] font-bold text-blue-600">25%</p></SummaryCard></section>
    <section className="surface overflow-hidden"><div className="flex flex-col gap-3 border-b border-slate-100 p-4 md:flex-row md:items-center"><div className="flex gap-5 text-xs font-semibold"><button className="border-b-2 border-blue-600 pb-3 text-blue-600">Todos</button><button className="pb-3 text-slate-500">Recentes</button><button className="pb-3 text-slate-500">Favoritos</button><button className="pb-3 text-slate-500">Lixeira</button></div><div className="ml-auto flex gap-2"><label className="relative"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-slate-400" /><input placeholder="Buscar materiais" className="h-10 w-full rounded-xl border border-slate-200 bg-slate-50 pl-9 pr-3 text-xs outline-none focus:border-blue-400 sm:w-56" /></label><button aria-label="Filtros" className="grid size-10 place-items-center rounded-xl border border-slate-200"><Filter className="size-4" /></button><button aria-label="Ordenar" className="grid size-10 place-items-center rounded-xl border border-slate-200"><ChevronDown className="size-4" /></button></div></div>
      <div className="grid xl:grid-cols-[210px_minmax(0,1fr)_300px]"><aside className="border-b border-slate-100 p-4 xl:border-b-0 xl:border-r"><div className="mb-3 flex items-center justify-between"><strong className="text-xs text-navy">Pastas</strong><button className="text-blue-600"><Plus className="size-4" /></button></div><nav className="space-y-1"><FolderItem active name="Direito Constitucional" count="8" /><FolderItem name="Administração" count="5" /><FolderItem name="Matemática" count="4" /><FolderItem name="Português" count="3" /><FolderItem name="Redação" count="2" /><FolderItem name="ENEM 2026" count="6" /></nav><div className="mt-6 border-t border-slate-100 pt-4"><strong className="text-xs text-navy">Tags populares</strong><div className="mt-3 flex flex-wrap gap-1.5">{["Direito", "Constitucional", "Matemática", "ENEM"].map(tag => <span key={tag} className="rounded-full bg-slate-100 px-2 py-1 text-[10px] text-slate-600">{tag}</span>)}</div></div></aside>
        <div className="min-w-0 divide-y divide-slate-100">{materials.map((item) => <button key={item.title} onClick={() => setSelected(item)} className={`grid w-full grid-cols-[36px_minmax(150px,1.5fr)_minmax(100px,.8fr)_110px_32px] items-center gap-3 p-4 text-left text-xs transition hover:bg-slate-50 ${selected.title === item.title ? "bg-blue-50/50" : ""}`}><span className={`grid size-9 place-items-center rounded-lg ${item.type === "PDF" ? "bg-red-50 text-red-500" : item.type === "DOCX" ? "bg-blue-50 text-blue-600" : "bg-violet-50 text-violet-600"}`}><File className="size-4" /></span><span className="min-w-0"><strong className="block truncate text-navy">{item.title}</strong><small className="text-[10px] text-slate-500">{item.type} · {item.size}</small></span><span className="truncate text-slate-500">{item.subject}</span><Status value={item.status} /><MoreVertical className="size-4 text-slate-400" /></button>)}</div>
        <aside className="border-t border-slate-100 p-5 xl:border-l xl:border-t-0"><div className="flex items-start gap-3"><span className="grid size-10 place-items-center rounded-xl bg-red-50 text-red-500"><FileText className="size-5" /></span><div className="min-w-0 flex-1"><strong className="block text-xs leading-snug text-navy">{selected.title}</strong><small className="text-[10px] text-slate-500">{selected.type} · {selected.size}</small></div><Star className="size-4 text-slate-400" /></div><div className="mt-5 flex border-b border-slate-100 text-xs font-semibold"><button className="border-b-2 border-blue-600 px-2 pb-3 text-blue-600">Visão geral</button><button className="px-2 pb-3 text-slate-500">Resumo IA</button></div><div className="mt-5 space-y-3 text-xs"><Detail label="Assunto" value={selected.subject} /><Detail label="Status" value={selected.status} /><Detail label="Tamanho" value={selected.size} /><Detail label="Enviado em" value="Hoje às 09:15" /></div><div className="mt-5 rounded-xl bg-violet-50 p-4"><p className="flex items-center gap-2 text-xs font-bold text-violet-800"><Sparkles className="size-4" /> Insights da IA</p><div className="mt-3 space-y-2 text-[11px] text-violet-700"><p>8 tópicos principais</p><p>23 conceitos-chave</p><p>12 perguntas sugeridas</p></div></div><button className="primary-button mt-4 w-full">Gerar quiz deste material</button><button className="secondary-button mt-2 w-full"><Sparkles className="size-4" /> Resumir com IA</button></aside></div>
    </section>
  </div>;
}

function SummaryCard({ icon,label,value,detail,children }:{icon:React.ReactNode;label:string;value:string;detail:string;children?:React.ReactNode}) { return <article className="surface p-5"><div className="flex items-center justify-between"><span className="text-xs font-bold text-navy">{label}</span><span className="text-blue-600 [&>svg]:size-4">{icon}</span></div><div className="mt-4 flex items-baseline gap-2"><strong className="text-2xl text-navy">{value}</strong><small className="text-[10px] text-emerald-600">{detail}</small></div>{children}</article> }
function FolderItem({name,count,active=false}:{name:string;count:string;active?:boolean}) { return <button className={`flex h-9 w-full items-center gap-2 rounded-lg px-2 text-xs ${active?"bg-blue-50 font-bold text-blue-700":"text-slate-600 hover:bg-slate-50"}`}><Folder className="size-4" /><span className="truncate">{name}</span><span className="ml-auto">{count}</span></button> }
function Status({value}:{value:string}) { const ready=value==="Pronto"; return <span className={`truncate font-semibold ${ready?"text-emerald-600":value.startsWith("Processando")?"text-orange-500":"text-violet-600"}`}>{value}</span> }
function Detail({label,value}:{label:string;value:string}) { return <p className="flex justify-between gap-3"><span className="text-slate-500">{label}</span><strong className="text-right text-navy">{value}</strong></p> }
